id: 1
name: "Jiangxi ICPC2023 Formal Contests"
formal_name: "Jiangxi ICPC2023 Formal Contests"
start_time: "2023-05-21T10:00:00.000+08:00"
duration: "5:00:00.000"
scoreboard_freeze_duration: "1:00:00.000"
penalty_time: 20