problem_number: 12
problem1:
  id: 245375
  label: "A"
  name: "Problem A"
  ordinal: 1
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem2:
  id: 245376
  label: "B"
  name: "Problem B"
  ordinal: 2
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem3:
  id: 245378
  label: "C"
  name: "Problem C"
  ordinal: 3
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem4:
  id: 245381
  label: "D"
  name: "Problem D"
  ordinal: 4
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem5:
  id: 245393
  label: "E"
  name: "Problem E"
  ordinal: 5
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem6:
  id: 245395
  label: "F"
  name: "Problem F"
  ordinal: 6
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem7:
  id: 245396
  label: "G"
  name: "Problem G"
  ordinal: 7
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem8:
  id: 245409
  label: "H"
  name: "Problem H"
  ordinal: 8
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem9:
  id: 245410
  label: "I"
  name: "Problem I"
  ordinal: 9
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem10:
  id: 245411
  label: "J"
  name: "Problem J"
  ordinal: 10
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem11:
  id: 245412
  label: "K"
  name: "Problem K"
  ordinal: 11
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1
problem12:
  id: 245413
  label: "L"
  name: "Problem L"
  ordinal: 12
  color: "darkslategray"
  rgb: "#2b2821"
  test_data_count: 1
  time_limit: 1